services:
  - type: web
    name: lucy3000-api
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci --include=dev && npx prisma generate && npx vite build && npm run build:backend
    startCommand: npx prisma migrate deploy && node dist/backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: /api

    healthCheckPath: /health
