services:
  - type: web
    name: lucy3000-api
    env: node
    plan: free
    autoDeploy: true
    buildCommand: |
      npm ci
      npm run build:backend
      npx prisma generate
      chmod +x scripts/deploy.sh
    startCommand: bash scripts/deploy.sh
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
